language: python
sudo: false
matrix:
  include:
  - python: "2.7"
    env: TEST_TYPE=test
  - python: "2.7"
    env: TEST_TYPE=check
install:
  - pip install -e .
  - travis_retry pip install -r requirements-dev.txt
script:
  - make $TEST_TYPE
