language: python
python:
  - "2.7"
sudo: false
env:
  - TEST_TYPE=test
  - TEST_TYPE=check
install:
  - pip install -e .
  - travis_retry pip install -r requirements-dev.txt
script:
  - make $TEST_TYPE
